// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/molon/gomsg/pb/authpb/auth.proto

/*
Package authpb is a generated protocol buffer package.

It is generated from these files:
	github.com/molon/gomsg/pb/authpb/auth.proto

It has these top-level messages:
	AuthResponse
*/
package authpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthResponse struct {
	// 用户id
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	// 平台 mobile/desktop 或者 其他
	Platform string `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AuthResponse) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthResponse)(nil), "authpb.AuthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	// 鉴权
	Auth(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Auth(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/authpb.Auth/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	// 鉴权
	Auth(context.Context, *google_protobuf.Empty) (*AuthResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.Auth/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Auth(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Auth_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/molon/gomsg/pb/authpb/auth.proto",
}

func init() { proto.RegisterFile("github.com/molon/gomsg/pb/authpb/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0xcf, 0xc9, 0xcf, 0xd3, 0x4f, 0xcf, 0xcf,
	0x2d, 0x4e, 0xd7, 0x2f, 0x48, 0xd2, 0x4f, 0x2c, 0x2d, 0xc9, 0x80, 0x52, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0x6c, 0x10, 0x21, 0x29, 0xe9, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x7d, 0xb0,
	0x68, 0x52, 0x69, 0x9a, 0x7e, 0x6a, 0x6e, 0x41, 0x49, 0x25, 0x44, 0x91, 0x92, 0x0d, 0x17, 0x8f,
	0x63, 0x69, 0x49, 0x46, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x00, 0x17, 0x73,
	0x69, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x29, 0x24, 0xc5, 0xc5, 0x51,
	0x90, 0x93, 0x58, 0x92, 0x96, 0x5f, 0x94, 0x2b, 0xc1, 0x04, 0x16, 0x86, 0xf3, 0x8d, 0xec, 0xb8,
	0x58, 0x40, 0xba, 0x85, 0xcc, 0xa0, 0xb4, 0x98, 0x1e, 0xc4, 0x2e, 0x3d, 0x98, 0x5d, 0x7a, 0xae,
	0x20, 0xbb, 0xa4, 0x44, 0xf4, 0x20, 0x6e, 0xd1, 0x43, 0xb6, 0x4b, 0x89, 0xc1, 0x49, 0x29, 0x4a,
	0x81, 0x90, 0x8f, 0x92, 0xd8, 0xc0, 0x66, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x38,
	0x06, 0xe2, 0xfc, 0x00, 0x00, 0x00,
}
